---
- set_fact:
    vnet_rg: "rg-ess-vdi-vm-centralindia-spokenet-prod-01"
  when: vnet == 'vnet-ess-vdi-vm-centralindia-prod-01'

- set_fact:
    vnet_rg: "rg-ess-vdi-info-vm-useast-spokenet-prod-01"
  when: vnet == 'vnet-ess-vdi-info-vm-useast-prod-01'

- set_fact:
    vnet_rg: "rg-ess-vdi-info-users-useast-spokenet-prod-01"
  when: vnet == 'vnet-ess-vdi-info-users-useast-prod-01'  
  
- set_fact:
    vnet_rg: "rg-ess-vdi-vm-northeurope-spokenet-prod-01"
  when: vnet == 'vnet-ess-vdi-vm-northeurope-prod-01'  
- set_fact:
    vnet_rg: "rg-corp-nonprod-1-spokenet-nonprod-01"
  when: vnet == 'vnet-corp-nonprod-1-eastus-prod-01'
  
- set_fact:
    vnet_rg: "rg-corp-prod-1-spokenet-prod-01"
  when: vnet == 'vnet-corp-prod-1-eastus-prod-01'

- set_fact:
    vnet_rg: "rg-ess-shared-services-1-spokenet-prod-01"
  when: vnet == 'vnet-ess-shared-services-1-eastus-prod-01'
# tasks file for network_interface
- name: Create vnet interface card
  azure_rm_networkinterface:
    ad_user: "{{username}}"
    password: "{{password}}"
    subscription_id: "{{sub_id}}"
    resource_group: "{{rg_name}}"
    name: "{{hostname}}_nic"
    virtual_network:
      name: "{{vnet}}"
      resource_group: "{{vnet_rg}}"
    location: "{{region}}"
    subnet_name: "{{layer}}"
    create_with_security_group: false
    security_group:
      name: nsg-common-SSSG
      resource_group: rg-common-GlobalNetwork
    ip_configurations:
      - name: ipconfig1
        primary: True
        private_ip_allocation_method: Dynamic
    tags:
      Owner: "{{owner_email}}"
      AppID: "{{app_id}}"
  register: interface

